name: s3-code-push
on:  
  push:
    branches: 
      - "prod"
jobs: 
  sync-s3-job:
    name: push to s3 job
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: us-east-1
        run: |
          echo deploying changes to s3 on ${{env.AWS_REGION}} &&
          ls . &&
          aws s3 sync . s3://amz-s3-2193829183812093/
