name: s3-code-push
on:  
  push:
    branches: 
      - "prod"
jobs: 
  sync-s3-job:
    name: push to s3 job
    environment: secrets
    runs-on: ubuntu-latest
    steps:
      - name: checkout to code
        uses: actions/checkout@v3

      - name: hello world
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo deploying changes to S3 ${#AWS_ACCESS_KEY_ID}
